name: btl_ttcs
description: Ứng dụng quản lý nhiệm vụ
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.2.0
  cloud_firestore: 6.0.3
  firebase_auth: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.5.0
  firebase_messaging: 16.0.3
  flutter_local_notifications: ^17.2.2
  firebase_auth_web: ^6.0.4  # Đảm bảo hỗ trợ web nếu cần
  firebase_auth_platform_interface: ^8.1.3  # Tùy chọn, để đảm bảo tương thích
  intl: ^0.20.2  # Giảm xuống phiên bản này
  syncfusion_flutter_charts: ^31.1.23

flutter:
  uses-material-design: true
  assets:
    - assets/background_login.png

dev_dependencies:
  flutter_test:
    sdk: flutter