name: task_manager
description: Ứng dụng quản lý nhiệm vụ
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  uuid: ^4.5.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^31.1.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/background_login.png
    - assets/taskmng.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/taskmng.jpg"
  min_sdk_android: 21